### ISSUE TITLE
Issue building the react-spark:build command

### ISSUE THREAD

**Issue by obaid** [darrenmerrett/react-spark#3]
I ran into an issue while trying to build the app:

```php artisan react-spark:build```

gives me the following error:

```/Users/ob/Development/app/vendor/darrenmerrett/react-spark/src/gulpfile.js:9
elixir.config.js.browserify.plugins.push(
                           ^

TypeError: Cannot read property 'plugins' of undefined
    at Object.<anonymous> (/Users/ob/Development/app/vendor/darrenmerrett/react-spark/src/gulpfile.js:9:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/Users/ob/.nvm/versions/node/v6.4.0/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/ob/.nvm/versions/node/v6.4.0/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)```

**Comment by darrenmerrett** [comment]
Hi, can you post your package.json file here.

**Comment by obaid** [comment]
@darrenmerrett here you go:

```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8"
  },
  "dependencies": {
    "bootstrap": "^3.0.0",
    "jquery": "^2.1.4",
    "js-cookie": "^2.1.0",
    "laravel-elixir": "^6.0.0-11",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-vueify": "^2.0.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "moment": "^2.10.6",
    "promise": "^7.1.1",
    "react-spark-js": "^0.1.5",
    "sweetalert": "^1.1.3",
    "underscore": "^1.8.3",
    "urijs": "^1.17.0",
    "vue": "~2.0.1",
    "vue-resource": "^1.0.3"
  }
}
```

(edited to correct the package.json)

**Comment by darrenmerrett** [comment]
I've just added support for larval-elixir v6, if you do a composer update it should work.
